

/// <summary>
/// Provides an abstraction for two-factor token generators.
/// </summary>

import { AllowedPrimaryKeysSafe } from "../../contexts/index.js";
import { IUserManager } from "../identity/index.js";
import { IdentityUser } from "../types/index.js";

/// <typeparam name="TUser">The type encapsulating a user.</typeparam>
export interface IUserTwoFactorTokenProvider<TKey extends AllowedPrimaryKeysSafe, TUser extends IdentityUser<TKey>> {
    /// <summary>
    /// Generates a token for the specified user and purpose.
    /// </summary>
    /// <param name="purpose">The purpose the token will be used for.</param>
    /// <param name="manager">The UserManager{TUser} that can be used to retrieve user properties.</param>
    /// <param name="user">The user a token should be generated for.</param>
    /// <returns>
    /// The Promise that represents the asynchronous operation, containing the token for the specified
    /// user and purpose.
    /// </returns>
    /// <remarks>
    /// The purpose parameter allows a token generator to be used for multiple types of token whilst
    /// ensuring a token for one purpose cannot be used for another. For example if we specified a purpose of "Email"
    /// and validated it with the same purpose a token with the purpose of TOTP would not pass the check even if it was
    /// for the same user.
    ///
    /// Implementations of IUserTwoFactorTokenProvider{TUser} should validate that purpose is not null or empty to
    /// help with token separation.
    /// </remarks>
    generateAsync(purpose: string, manager: IUserManager<TKey, TUser>, user: TUser): Promise<string>;

    /// <summary>
    /// Returns a flag indicating whether the specified token is valid for the given
    /// user and purpose.
    /// </summary>
    /// <param name="purpose">The purpose the token will be used for.</param>
    /// <param name="token">The token to validate.</param>
    /// <param name="manager">The UserManager{TUser} that can be used to retrieve user properties.</param>
    /// <param name="user">The user a token should be validated for.</param>
    /// <returns>
    /// The Promise that represents the asynchronous operation, containing a flag indicating the result
    /// of validating the token for the specified user and purpose.
    /// The Promise will return true if the token is valid, otherwise false.
    /// </returns>
    validateAsync(purpose: string, token: string, manager: IUserManager<TKey, TUser>, user: TUser): Promise<boolean>;

    /// <summary>
    /// Returns a flag indicating whether the token provider can generate a token suitable for two-factor authentication token for
    /// the specified user.
    /// </summary>
    /// <param name="manager">The UserManager{TUser} that can be used to retrieve user properties.</param>
    /// <param name="user">The user a token could be generated for.</param>
    /// <returns>
    /// The Promise that represents the asynchronous operation, containing a flag indicating if a two
    /// factor token could be generated by this provider for the specified user.
    /// The Promise will return true if a two-factor authentication token could be generated, otherwise false.
    /// </returns>
    canGenerateTwoFactorTokenAsync(manager: IUserManager<TKey, TUser>, user: TUser): Promise<boolean>;
}
