
import { AllowedPrimaryKeysSafe } from "../../contexts/index.js";
import { ArgumentNullThrowHelper } from "../../types/exception.js";
import { IUserManager } from "../identity/index.js";
import { IdentityUser } from "../types/index.js";
import { TotpSecurityStampBasedTokenProvider } from "./totp.security_stamp_based.token.provider.js";

/// <summary>
/// TokenProvider that generates tokens from the user's security stamp and notifies a user via email.
/// </summary>
/// <typeparam name="TUser">The type used to represent a user.</typeparam>
export class PhoneNumberTokenProvider<TKey extends AllowedPrimaryKeysSafe, TUser extends IdentityUser<TKey>> extends TotpSecurityStampBasedTokenProvider<TKey, TUser> {
    /// <summary>
    /// Returns a flag indicating whether the token provider can generate a token suitable for two-factor authentication token for
    /// the specified <paramref name="user"/>.
    /// </summary>
    /// <param name="manager">The <see cref="UserManager{TUser}"/> that can be used to retrieve user properties.</param>
    /// <param name="user">The user a token could be generated for.</param>
    /// <returns>
    /// The <see cref="Task"/> that represents the asynchronous operation, containing the a flag indicating if a two
    /// factor token could be generated by this provider for the specified <paramref name="user"/>.
    /// The task will return true if a two-factor authentication token could be generated as the user has
    /// a telephone number, otherwise false.
    /// </returns>
    public override async canGenerateTwoFactorTokenAsync(manager: IUserManager<TKey, TUser>, user:  TUser): Promise<boolean>
    {
        ArgumentNullThrowHelper.throwIfNull(manager);
        
        let phoneNumber = await manager.getPhoneNumberAsync(user);

        return !!phoneNumber && await manager.isPhoneNumberConfirmedAsync(user);
    }

    /// <summary>
    /// Returns a constant, provider and user unique modifier used for entropy in generated tokens from user information.
    /// </summary>
    /// <param name="purpose">The purpose the token will be generated for.</param>
    /// <param name="manager">The <see cref="UserManager{TUser}"/> that can be used to retrieve user properties.</param>
    /// <param name="user">The user a token should be generated for.</param>
    /// <returns>
    /// The <see cref="Task"/> that represents the asynchronous operation, containing a constant modifier for the specified
    /// <paramref name="user"/> and <paramref name="purpose"/>.
    /// </returns>
    public override async getUserModifierAsync(purpose: string, manager: IUserManager<TKey, TUser>, user:  TUser): Promise<string>
    {
        ArgumentNullThrowHelper.throwIfNull(manager);

        let phoneNumber = await manager.getPhoneNumberAsync(user);

        return `PhoneNumber:${purpose}:${phoneNumber}`;
    }
}
