// export const TOKENS = {

    // KEY_NORMALIZER  : Symbol("KEY_NORMALIZER"),
    // PASSWORD_HASHER : Symbol("PASSWORD_HASHER"),
    // Validators
    // PASSWORD_VALIDATORS: Symbol("PASSWORD_VALIDATORS"),
    // ROLE_VALIDATORS : Symbol("ROLE_VALIDATORS"),
    // USER_VALIDATORS : Symbol("USER_VALIDATORS"),

    // Metrics
    // METER_FACTORY: Symbol("METER_FACTORY"),
    // AUTHORIZATION_METRICS: Symbol("AUTHORIZATION_METRICS"),

    // Authorization
    // AUTHORIZATION_POLICY_PROVIDER   : Symbol("AUTHORIZATION_POLICY_PROVIDER"),
    // AUTHORIZATION_HANDLER_PROVIDER  : Symbol("AUTHORIZATION_HANDLER_PROVIDER"),
    // AUTHORIZATION_HANDLER_CONTEXT_FACTORY: Symbol("AUTHORIZATION_HANDLER_CONTEXT_FACTORY"),

    // AUTHORIZATION_EVALUATOR : Symbol("AUTHORIZATION_EVALUATOR"),
    // AUTHORIZATION_SERVICE   : Symbol("AUTHORIZATION_SERVICE"),

    // Policy Authorization
    // POLICY_AUTHORIZATION_SERVICE: Symbol("POLICY_AUTHORIZATION_SERVICE"),

    // Identity Managers
    // USER_MANAGER : Symbol("USER_MANAGER"),
    // USER_MANAGER1: Symbol("USER_MANAGER1"),
    // ROLE_MANAGER : Symbol("ROLE_MANAGER"),

// };
